version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "pip"
      - "dependencies"
    allow:
      - dependency-name: "slack-bolt"